apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: 12007158/multi-worker
      ports:
        - containerPort: 3000


# to get the latest version from docker hub use version number while building the docker
# docker build 12007158/multi-client:v5 .
