apiVersion: app/v1
kind: Deployment
metadata:
  name: client-deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: 12007158/multi-client
          ports:
            - containerPort : 3000 



# to get the latest version from docker hub use version number while building the docker
# docker build 12007158/multi-client:v5 .

# kubectl set image  typeof object/<object_name> <container_name> =<new image to use>
#run kubectl command
# kubectl set image deployment/client-deployment  client=12007158/multi-client :v5